services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - "${API_PORT}:${API_PORT}"
    networks:
      - app_network

networks:
  app_network:
